/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin-users'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as HostsRouteImport } from './routes/hosts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as CustomerCustomerIdRouteImport } from './routes/customer.$customerId'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalLoginRouteImport } from './routes/portal/login'
import { Route as PortalStatusRouteImport } from './routes/portal/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsRoute = HostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCustomerIdRoute = CustomerCustomerIdRouteImport.update({
  id: '/customer/$customerId',
  path: '/customer/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalStatusRoute = PortalStatusRouteImport.update({
  id: '/portal/status',
  path: '/portal/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-users': typeof AdminUsersRoute
  '/customers': typeof CustomersRoute
  '/hosts': typeof HostsRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/customer/$customerId': typeof CustomerCustomerIdRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/status': typeof PortalStatusRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-users': typeof AdminUsersRoute
  '/customers': typeof CustomersRoute
  '/hosts': typeof HostsRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/customer/$customerId': typeof CustomerCustomerIdRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/status': typeof PortalStatusRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-users': typeof AdminUsersRoute
  '/customers': typeof CustomersRoute
  '/hosts': typeof HostsRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/customer/$customerId': typeof CustomerCustomerIdRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/status': typeof PortalStatusRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-users'
    | '/customers'
    | '/hosts'
    | '/login'
    | '/plans'
    | '/customer/$customerId'
    | '/portal/login'
    | '/portal/status'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-users'
    | '/customers'
    | '/hosts'
    | '/login'
    | '/plans'
    | '/customer/$customerId'
    | '/portal/login'
    | '/portal/status'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/admin-users'
    | '/customers'
    | '/hosts'
    | '/login'
    | '/plans'
    | '/customer/$customerId'
    | '/portal/login'
    | '/portal/status'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CustomersRoute: typeof CustomersRoute
  HostsRoute: typeof HostsRoute
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  CustomerCustomerIdRoute: typeof CustomerCustomerIdRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalStatusRoute: typeof PortalStatusRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-users': {
      id: '/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts': {
      id: '/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof HostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/$customerId': {
      id: '/customer/$customerId'
      path: '/customer/$customerId'
      fullPath: '/customer/$customerId'
      preLoaderRoute: typeof CustomerCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/status': {
      id: '/portal/status'
      path: '/portal/status'
      fullPath: '/portal/status'
      preLoaderRoute: typeof PortalStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminUsersRoute: AdminUsersRoute,
  CustomersRoute: CustomersRoute,
  HostsRoute: HostsRoute,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  CustomerCustomerIdRoute: CustomerCustomerIdRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalStatusRoute: PortalStatusRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
